language: python

python:
  - 3.5

services:
  - postgresql

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

git:
  depth: 3

env:
  global:
    - PG_DATABASE=inferno
    - PYTHON=python

  matrix:
    - TASK=test
    - TASK=calls-day-2017-05-20

before_install:
  - pip install coverage
  - psql --version
  - make --version
  - git clone https://github.com/fitnr/gtfs-sql-importer.git
  - make -e init drop_constraints -C gtfs-sql-importer
  - psql $PG_DATABASE -c "select postgis_full_version()"
  - psql $PG_DATABASE -f src/test_data/positions.sql
  - psql $PG_DATABASE -c "truncate table rt_vehicle_positions"

install: make -e init

script: make -e $TASK

after_script:
    - psql $PG_DATABASE -c "SELECT * FROM calls LIMIT 10"
    - "[[ $TASK = test ]] && coverage report --show-missing --include=src/*"
