language: python

python:
  - 3.5

services: 
  - postgresql

git:
  depth: 3

before_install:
  - createdb nycbus

install:
  - make init DATABASE=nycbus
  - pip install coverage
  - psql nycbus -q -f src/test_data/schema.sql 
  - psql nycbus -q -f src/test_data/positions.sql -f src/test_data/stop_times.sql
  - psql nycbus -q -f src/test_data/trips.sql -f src/test_data/stop_distances.sql

script:
    - make test PYTHON=python
    - make calls-day-2017-01-01 PYTHON=python DATABASE=nycbus

after_script:
    - psql -U postgres -c "SELECT * FROM calls LIMIT 10"
    - coverage report
