language: python

python:
  - 3.5

services: 
  - postgresql

git:
  depth: 3

before_install:
  - pip install coverage

install:
  - curl -LO https://github.com/fitnr/gtfs-sql-importer/archive/master.zip
  - unzip master.zip
  - make init drop_constraints -C gtfs_SQL_importer-master DATABASE=inferno
  - make init DATABASE=inferno

script:
    - make test PYTHON=python DATABASE=inferno
    - psql inferno -c 'TRUNCATE TABLE calls'
    - make calls-day-2017-05-20 PYTHON=python DATABASE=inferno

after_script:
    - psql inferno -c "SELECT * FROM calls LIMIT 10"
    - coverage report --show-missing --include=src/*
