name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgis/postgis:10-2.5
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 13s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 2s
    env:
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: localhost
      PAGER: cat
      DATE: 2017-05-19

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            test-requirements.txt

      - run: pip install -r test-requirements.txt

      - name: Load test data
        run: make load-test

      - run: make init

      - name: Infer calls for a test day
        run: make calls-day-2017-05-20
        env:
          INFERNOFLAGS: --epsg=3627

      - name: Run python tests
        run: make test

      - name: Check on results
        run: psql -c "SELECT * FROM inferno.calls LIMIT 10"
